/**
 * Minimal ESLint flat config for classic browser scripts (no ES modules).
 * Goal: catch undefined identifiers / eval — not style wars.
 * No eslint plugins required beyond `eslint` itself.
 */
'use strict';

/** Minimal browser + Node globals (avoid extra `globals` package). */
const envGlobals = {
  // browser
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  location: 'readonly',
  navigator: 'readonly',
  history: 'readonly',
  fetch: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  AbortController: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  MutationObserver: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  matchMedia: 'readonly',
  getComputedStyle: 'readonly',
  HTMLElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  DOMParser: 'readonly',
  crypto: 'readonly',
  indexedDB: 'readonly',
  caches: 'readonly',
  serviceWorker: 'readonly',
  Notification: 'readonly',
  // GIS / Google (optional)
  google: 'readonly',
  gapi: 'readonly',
  // node interop in pure modules
  module: 'readonly',
  exports: 'writable',
  require: 'readonly',
  process: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  Buffer: 'readonly',
  global: 'readonly',
};

/** Shared names from classic script load order (index.html). */
const appGlobals = {
  DURATION_LIMITS: 'readonly',
  formatClockTime: 'readonly',
  formatTimeRange: 'readonly',
  formatDurationHours: 'readonly',
  formatDurationHoursI18n: 'readonly',
  formatHoursCompact: 'readonly',
  decimalHoursToParts: 'readonly',
  partsToDecimalHours: 'readonly',
  isValidWeekendDuration: 'readonly',
  isValidPrzedPoDuration: 'readonly',
  buildHolidays: 'readonly',
  shiftHours: 'readonly',
  isWolne: 'readonly',
  escapeHtml: 'readonly',
  daysInMonthCal: 'readonly',
  monthNames: 'writable',
  monthNamesShort: 'writable',
  monthNamesGenitive: 'writable',
  dayNames: 'writable',
  factorySchedule: 'writable',
  factoryMonthHours: 'writable',
  scheduleRegistry: 'writable',
  registerSchedule: 'readonly',
  registerYearData: 'readonly',
  t: 'readonly',
  prefs: 'writable',
  notes: 'writable',
  overtimes: 'writable',
  urlops: 'writable',
  customSchedule: 'writable',
  showToast: 'readonly',
  showModal: 'readonly',
  hideModal: 'readonly',
  closeSideMenu: 'readonly',
  refreshViews: 'readonly',
  getElementByIdSafe: 'readonly',
  categorizeOvertime: 'readonly',
  calcOvertimeTime: 'readonly',
  getOvertimes: 'readonly',
  setOvertime: 'readonly',
  removeOvertime: 'readonly',
  getMonthOvertimeSummary: 'readonly',
  getActualWorkTime: 'readonly',
  loginDrive: 'readonly',
  logoutDrive: 'readonly',
  isDriveLoggedIn: 'readonly',
  isDriveTokenValid: 'readonly',
  updateDriveUI: 'readonly',
  driveFeatureOn: 'readonly',
  openDriveSyncOptionsPanel: 'readonly',
  renderReliefTimeline: 'readonly',
  renderCycleTimeline: 'readonly',
  renderFlowSegmentWidget: 'readonly',
  bindFlowSegmentToggle: 'readonly',
};

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'tests/**',
      'tools/**',
      'js/i18n/pl.js',
      'js/i18n/en.js',
      'js/i18n/uk.js',
      'js/schedules/gillette/**',
      'sw.js',
      'eslint.config.js',
    ],
  },
  {
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...envGlobals,
        ...appGlobals,
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-debugger': 'error',
      eqeqeq: ['warn', 'smart'],
    },
  },
];
